name: release_updater
description: A simple way to automatically update release/installation files in a local directory.
version: 1.0.23
homepage: https://github.com/gmpassos/release_updater

environment:
  sdk: '>=2.14.4 <3.0.0'

executables:
  release_updater:
  release_updater_server:
  release_packer:


dependencies:
  archive: ^3.1.8
  mercury_client: ^2.1.3
  path: ^1.8.1
  pub_semver: ^2.1.0
  shelf: ^1.2.0
  shelf_static: ^1.1.0
  shelf_gzip: ^4.0.0
  crypto: ^3.0.1
  base_codecs: ^1.0.1
  collection: ^1.15.0
  yaml: ^3.1.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  dependency_validator: ^3.1.2
  coverage: ^1.0.3
  pubspec: ^2.0.1
