name: release_updater
description: A simple way to update release/installation files in a local directory.
version: 1.0.0
homepage: https://github.com/gmpassos/release_updater

environment:
  sdk: '>=2.14.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
