name: release_updater
description: A simple way to automatically update release/installation files in a local directory.
version: 1.1.10
homepage: https://github.com/gmpassos/release_updater

environment:
  sdk: '>=3.5.0 <4.0.0'

executables:
  release_updater:
  release_updater_server:
  release_packer:
  release_utility:


dependencies:
  data_serializer: ^1.2.1
  ascii_art_tree: ^1.0.6
  mercury_client: ^2.2.4
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  shelf_gzip: ^4.1.0
  gcloud: ^0.8.18
  googleapis_auth: ^1.6.0
  crypto: ^3.0.6
  path: ^1.9.1
  pub_semver: ^2.1.4
  base_codecs: ^1.0.1
  archive: ^3.6.1
  collection: ^1.19.1
  yaml: ^3.1.2


dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.11
  dependency_validator: ^3.2.3
  coverage: ^1.11.0
  pubspec: ^2.3.0

#dependency_overrides:
#  ascii_art_tree:
#    path: ../ascii_art_tree
