name: release_updater
description: A simple way to automatically update release/installation files in a local directory.
version: 1.1.11
homepage: https://github.com/gmpassos/release_updater

environment:
  sdk: '>=3.6.0 <4.0.0'

executables:
  release_updater:
  release_updater_server:
  release_packer:
  release_utility:


dependencies:
  data_serializer: ^1.2.1
  ascii_art_tree: ^1.0.6
  mercury_client: ^2.3.0
  shelf: ^1.4.2
  shelf_static: ^1.1.3
  shelf_gzip: ^4.1.0
  gcloud: ^0.8.18
  googleapis_auth: ^1.6.0
  crypto: ^3.0.6
  path: ^1.9.1
  pub_semver: ^2.1.5
  base_codecs: ^1.0.1
  archive: ^4.0.4
  collection: ^1.19.1
  yaml: ^3.1.3


dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  dependency_validator: ^5.0.2
  coverage: ^1.11.1
  pubspec: ^2.3.0

#dependency_overrides:
#  ascii_art_tree:
#    path: ../ascii_art_tree
