name: release_updater
description: A simple way to automatically update release/installation files in a local directory.
version: 1.1.4
homepage: https://github.com/gmpassos/release_updater

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  release_updater:
  release_updater_server:
  release_packer:
  release_utility:


dependencies:
  archive: ^3.3.7
  mercury_client: ^2.1.8
  path: ^1.8.3
  pub_semver: ^2.1.4
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_gzip: ^4.0.1
  crypto: ^3.0.3
  base_codecs: ^1.0.1
  data_serializer: ^1.0.10
  collection: ^1.17.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.1
  dependency_validator: ^3.2.2
  coverage: ^1.6.3
  pubspec: ^2.3.0
