name: release_updater
description: A simple way to automatically update release/installation files in a local directory.
version: 1.1.7
homepage: https://github.com/gmpassos/release_updater

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  release_updater:
  release_updater_server:
  release_packer:
  release_utility:


dependencies:
  data_serializer: ^1.0.12
  ascii_art_tree: ^1.0.6
  mercury_client: ^2.2.0
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  shelf_gzip: ^4.0.1
  gcloud: ^0.8.11
  googleapis_auth: ^1.4.1
  crypto: ^3.0.3
  path: ^1.8.3
  pub_semver: ^2.1.4
  base_codecs: ^1.0.1
  archive: ^3.4.9
  collection: ^1.17.1
  yaml: ^3.1.2


dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.9
  dependency_validator: ^3.2.3
  coverage: ^1.7.1
  pubspec: ^2.3.0

#dependency_overrides:
#  ascii_art_tree:
#    path: ../ascii_art_tree
