name: release_updater
description: A simple way to automatically update release/installation files in a local directory.
version: 1.0.24
homepage: https://github.com/gmpassos/release_updater

environment:
  sdk: '>=2.14.4 <3.0.0'

executables:
  release_updater:
  release_updater_server:
  release_packer:


dependencies:
  archive: ^3.3.1
  mercury_client: ^2.1.6
  path: ^1.8.2
  pub_semver: ^2.1.1
  shelf: ^1.3.2
  shelf_static: ^1.1.1
  shelf_gzip: ^4.0.0
  crypto: ^3.0.2
  base_codecs: ^1.0.1
  collection: ^1.16.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  dependency_validator: ^3.2.2
  coverage: ^1.5.0
  pubspec: ^2.3.0
